### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by amlmn**
Add issues templates for:
  * site bug reports
  * article bug reports
  * algorithm proposals

### CODE REVIEW

**Review by wbthomason — APPROVED** [review]
Looks good to me

**Review by wbthomason — CHANGES_REQUESTED** [review]
Actually. Can these go to a different branch? I don't think `master` is the right place.

**Comment by amlmn** [comment]
> Actually. Can these go to a different branch? I don't think `master` is the right place.

We talked a little bit about this out-of-band. Do you still want them in a different branch?

**Review by wbthomason — APPROVED** [review]
Per out of band discussion, I'm fine with these going in `master`.

**Pull request merged**
